name: Python App Workflow

on:
  workflow_dispatch:

jobs:
  run_python_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: latest  # Use the latest available Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your actual requirements file if needed

    - name: Run Python App
      run: python main.py
